import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowLeft, ArrowRight, BrainCircuit, CheckCircle2, ChevronRight, CircleAlert, FileSearch, Network, ScanSearch, ShieldCheck, Sparkles } from "lucide-react";
import "./style.css";

const Metric = ({ value, label, tone = "green" }: { value: string; label: string; tone?: "green" | "blue" | "red" }) => <div className={`metric ${tone}`}><b>{value}</b><span>{label}</span></div>;
const Tag = ({ children }: { children: React.ReactNode }) => <span className="tag">{children}</span>;
const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`card ${className}`}>{children}</section>;

function Title() { return <div className="title-slide"><div className="signal">● SYSTEM ONLINE</div><div className="hero-mark"><ShieldCheck size={68} /></div><p className="eyebrow">AI VERIFICATION PLATFORM</p><h1>Climate<br /><em>Veritas</em></h1><p className="lede">Plataforma neuro-simbólica para la detección asistida de desinformación ambiental.</p><div className="tags"><Tag>TF-IDF + BERT-tiny</Tag><Tag>Ontologías ambientales</Tag><Tag>Evidencia curada</Tag></div><p className="hint">Usa ← → o espacio para navegar</p></div> }
function Problem() { return <Slide eyebrow="01 · CONTEXTO" title="Desinformación ambiental: un problema de precisión"><div className="split"><div><p className="lede">Una afirmación puede sonar plausible y aun así negar relaciones científicas establecidas. La clasificación por texto no basta por sí sola.</p><div className="problem-list"><Point icon={<FileSearch />} title="Lenguaje ambiguo" text="La redacción puede ocultar, simplificar o distorsionar una afirmación científica." /><Point icon={<Network />} title="Conocimiento explícito" text="Algunas contradicciones deben poder detectarse y explicarse mediante reglas." /><Point icon={<CircleAlert />} title="Revisión humana" text="El resultado es una señal trazable para apoyar, no sustituir, el fact-checking." /></div></div><Card className="quote"><span>“CO₂ no contribuye al calentamiento global.”</span><div><b>Modelo textual</b><i>puede discrepar</i></div><div className="verdict"><CircleAlert /> Contradicción ontológica → FAKE</div></Card></div></Slide> }
function System() { return <Slide eyebrow="02 · PROPUESTA" title="Un sistema híbrido, explicable y orientado a evidencia"><p className="lede">Climate Veritas combina señales estadísticas, conocimiento simbólico y recuperación selectiva de evidencia para analizar afirmaciones ambientales.</p><div className="three"><Card><BrainCircuit /><h3>Aprendizaje automático</h3><p>Representaciones léxicas, contextuales y un clasificador balanceado estiman la probabilidad.</p></Card><Card><Network /><h3>Reglas ontológicas</h3><p>Relaciones ambientales canónicas se usan para detectar conflictos explícitos.</p></Card><Card><ScanSearch /><h3>Evidencia curada</h3><p>La recuperación semántica permite respaldar o refutar coincidencias de alta confianza.</p></Card></div></Slide> }
function Architecture() { return <Slide eyebrow="03 · ARQUITECTURA" title="Flujo de análisis neuro-simbólico"><div className="architecture"><Node icon={<FileSearch />} label="Afirmación" sub="texto o claim" /><Arrow /><Node icon={<Sparkles />} label="NLP" sub="normalización + NER" /><Arrow /><Node icon={<Network />} label="Conocimiento" sub="enlace + reglas RDF" /><Arrow /><Node icon={<BrainCircuit />} label="Modelo híbrido" sub="TF-IDF + BERT + RF" /><Arrow /><Node icon={<ShieldCheck />} label="Respuesta" sub="veredicto explicable" /></div><div className="rule-band"><b>Regla de seguridad</b><span>Si existe una contradicción ontológica explícita, la decisión final se fuerza a <strong>FAKE</strong>, aunque el modelo estadístico prediga REAL.</span></div></Slide> }
function Pipeline() { return <Slide eyebrow="04 · PIPELINE" title="De la afirmación a una respuesta trazable"><div className="steps"><Step n="01" title="Normalizar claim" text="Se usa la afirmación enviada o una normalización ligera del texto." /><Step n="02" title="Extraer entidades" text="spaCy y un diccionario de dominio identifican CO₂, CH₄, clima, energía y biodiversidad." /><Step n="03" title="Evaluar conocimiento" text="RDFLib enlaza conceptos y detecta soporte o contradicciones semánticas." /><Step n="04" title="Predecir y explicar" text="Se integran el modelo, las reglas y la evidencia recuperada en una respuesta JSON." /></div></Slide> }
function Model() { return <Slide eyebrow="05 · MODELO" title="Representación híbrida de la afirmación"><div className="model-flow"><div><b>TF-IDF</b><small>unigramas + bigramas</small></div><span>+</span><div><b>Señales textuales</b><small>longitud y legibilidad</small></div><span>+</span><div><b>Señales simbólicas</b><small>entidades y conflicto</small></div><span>+</span><div><b>BERT-tiny</b><small>embedding CLS · 128D</small></div></div><div className="down">↓</div><Card className="classifier"><BrainCircuit /><div><p className="eyebrow">CLASIFICADOR PROMOVIDO</p><h2>Random Forest <span>balanceado</span></h2><p>Umbral calibrado para REAL: <strong>0.56</strong>. El encoder configurado para CPU es <code>prajjwal1/bert-tiny</code>.</p></div></Card></Slide> }
function Evidence() { return <Slide eyebrow="06 · VERIFICACIÓN" title="Evidencia: intervenir solo cuando la señal es fuerte"><div className="split"><Card><p className="eyebrow">RECUPERACIÓN SELECTIVA</p><h2>Claims curados + similitud TF-IDF</h2><p>Se comparan las afirmaciones con correcciones y abstracts climáticos. Una coincidencia débil no se presenta como prueba.</p><div className="status-grid"><Status label="SUPPORTED" text="evidencia respalda" tone="green" /><Status label="REFUTED" text="evidencia refuta" tone="red" /><Status label="INSUFFICIENT" text="no anula el modelo" tone="blue" /></div></Card><div className="result-demo"><p className="eyebrow">RESPUESTA EXPLICABLE</p><div className="fake">FAKE <small>94% confidence</small></div><p>“La afirmación contradice una relación ambiental conocida.”</p><Tag>Entidad: CO₂</Tag> <Tag>Regla: contributes_to warming</Tag></div></div></Slide> }
function Experiments() { return <Slide eyebrow="07 · EXPERIMENTOS" title="Evaluar antes de promover"><div className="metrics"><Metric value="1,004" label="registros de entrenamiento" /><Metric value="200" label="casos de holdout balanceado" tone="blue" /><Metric value="5 folds" label="validación cruzada estratificada" tone="green" /></div><div className="experiment-grid"><Card><h3>Protocolos que evitan fuga</h3><ul><li>TF-IDF se ajusta dentro de cada fold.</li><li>El holdout se excluye antes de entrenar.</li><li>El umbral se calibra con predicciones out-of-fold.</li></ul></Card><Card><h3>Criterio operativo</h3><p>Además de accuracy, se priorizan <strong>macro-F1</strong>, balanced accuracy y el recall de <strong>FAKE</strong>.</p><div className="target">Objetivo: capturar más desinformación sin presentar CV interna como generalización.</div></Card></div></Slide> }
function Results() { return <Slide eyebrow="08 · RESULTADOS" title="El artefacto de producción se eligió con benchmark retenido"><div className="result-metrics"><Metric value="82.5%" label="accuracy en holdout" /><Metric value="0.8237" label="macro-F1 en holdout" /><Metric value="91.0%" label="recall FAKE" tone="red" /></div><div className="compare"><div className="compare-head"><span>Modelo evaluado sin ver el benchmark</span><span>Macro-F1</span><span>Recall FAKE</span></div><div><b>holdout_bert · híbrido BERT + RF</b><strong>0.8237</strong><strong className="hi">0.9100</strong></div><div><b>word + char · Logistic Regression</b><strong>0.7947</strong><strong>0.7600</strong></div></div><p className="footnote">Se promovió <code>holdout_bert</code>: ofreció mayor macro-F1 y menor probabilidad de dejar pasar afirmaciones FAKE en el benchmark retenido.</p></Slide> }
function Negation() { return <Slide eyebrow="09 · HALLAZGO" title="Las negaciones cambian el significado"><div className="negation"><Card><p className="eyebrow">PROBLEMA DETECTADO</p><h2>Eliminar <em>not</em>, <em>no</em> o <em>without</em> borra señal crítica.</h2><p>El stop-word list original de inglés podía eliminar tokens esenciales para fact-checking.</p></Card><Card className="improvement"><p className="eyebrow">COMPARACIÓN · 5 FOLDS</p><div><Metric value="0.7022" label="macro-F1 · TF-IDF legado" tone="red" /><ChevronRight /><Metric value="0.7211" label="conservando negación" tone="blue" /><ChevronRight /><Metric value="0.7404" label="palabra + carácter" /></div><p>Las reglas críticas de negación obtuvieron <strong>7/7 PASS</strong>.</p></Card></div></Slide> }
function Limits() { return <Slide eyebrow="10 · LÍMITES Y SIGUIENTE PASO" title="Lo que el sistema afirma — y lo que no"><div className="three"><Card><CheckCircle2 /><h3>Sí aporta</h3><p>Una señal explicable, reglas auditables, evidencia recuperada y comparación reproducible de experimentos.</p></Card><Card><CircleAlert /><h3>No reemplaza</h3><p>La revisión científica o periodística. La confianza no equivale a certeza factual universal.</p></Card><Card><Sparkles /><h3>Siguiente experimento</h3><p>Reevaluar el híbrido consciente de negación excluyendo el holdout y sumar una fuente externa independiente.</p></Card></div><div className="closing">Climate Veritas · precisión estadística + conocimiento explícito + revisión humana</div></Slide> }
function Arrow() { return <div className="arrow"><ArrowRight /></div> } function Node({ icon, label, sub }: { icon: React.ReactNode; label: string; sub: string }) { return <Card className="node">{icon}<b>{label}</b><small>{sub}</small></Card> } function Point({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="point">{icon}<div><b>{title}</b><p>{text}</p></div></div> } function Step({ n, title, text }: { n: string; title: string; text: string }) { return <Card className="step"><span>{n}</span><h3>{title}</h3><p>{text}</p></Card> } function Status({ label, text, tone }: { label: string; text: string; tone: string }) { return <div className={`status ${tone}`}><b>{label}</b><span>{text}</span></div> }
function Slide({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="slide"><header><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></header>{children}</div> }
const slides = [Title, Problem, System, Architecture, Pipeline, Model, Evidence, Experiments, Results, Negation, Limits];
function App() { const [index, setIndex] = useState(0); const go = (n: number) => setIndex(Math.max(0, Math.min(slides.length - 1, n))); useEffect(() => { const key = (e: KeyboardEvent) => { if (["ArrowRight", " ", "PageDown"].includes(e.key)) go(index + 1); if (["ArrowLeft", "PageUp"].includes(e.key)) go(index - 1); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [index]); const Current = slides[index]; return <main><div className="grid" /><div className="orb one" /><div className="orb two" /><Current /><footer><span className="counter">{String(index + 1).padStart(2, "0")} <i /> {String(slides.length).padStart(2, "0")}</span><div className="progress"><span style={{ width: `${((index + 1) / slides.length) * 100}%` }} /></div><div className="controls"><button onClick={() => go(index - 1)} disabled={!index}><ArrowLeft /></button><button onClick={() => go(index + 1)} disabled={index === slides.length - 1}><ArrowRight /></button></div></footer></main> }
createRoot(document.getElementById("root")!).render(<App />);
