-- Climate Veritas · Esquema PostgreSQL reproducible
--
-- Uso:
--   createdb fakenews-clima
--   psql -d fakenews-clima -f docs/schema.sql
--   psql -d fakenews-clima -f docs/database_data.sql  -- si se generó el volcado de datos
--
-- Este archivo define el esquema. Los datos de entrenamiento y evidencia se
-- exportan por separado con `python scripts/export_database_dump.py` para no
-- mezclar DDL versionado con datos que cambian. El historial de predicciones no
-- se exporta por defecto porque puede contener publicaciones introducidas por
-- usuarios durante las pruebas.

BEGIN;

CREATE TABLE IF NOT EXISTS dataset_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text TEXT NOT NULL,
    extracted_claim TEXT,
    label VARCHAR(10) NOT NULL,
    category VARCHAR(50),
    source VARCHAR(100) NOT NULL DEFAULT 'climate-fever',
    CONSTRAINT ck_dataset_records_label CHECK (label IN ('REAL', 'FAKE'))
);

CREATE TABLE IF NOT EXISTS dataset_evidence (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_record_id INTEGER NOT NULL,
    source_dataset VARCHAR(100) NOT NULL,
    source_url VARCHAR(500),
    evidence_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dataset_evidence_dataset_record
        FOREIGN KEY (dataset_record_id)
        REFERENCES dataset_records(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_dataset_evidence_dataset_record_id
    ON dataset_evidence (dataset_record_id);

CREATE TABLE IF NOT EXISTS prediction_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_text TEXT NOT NULL,
    extracted_claim TEXT,
    category VARCHAR(50),
    detected_entities JSONB,
    ontological_conflicts JSONB,
    prediction VARCHAR(10) NOT NULL,
    confidence_score DOUBLE PRECISION NOT NULL,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_prediction_history_prediction CHECK (prediction IN ('REAL', 'FAKE'))
);

COMMIT;
